# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      PGDATA: /tmp
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080